version: '3.7'

services:
  web:
    build: ./libations/
    command: gunicorn drinks.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./libations/:/usr/src/libations/
      - static_volume:/usr/src/libations/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/libations/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: